favicon: null
name: LukeTherien
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.575211490271613
  brandStrength: 0.1295090964995325
  rhythmicContrast: 0.06161467707715929
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.05456283548846841
typography_spectrum: 0.5290011
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2344818073324859
analytics:
  twitter: null
  google: null
  facebook: null
